#!/usr/bin/env python3
"""
NotebookLM Integration - Automatic CV/Cover Letter Upload
==========================================================
Automatically uploads all generated resumes and cover letters to a dedicated NotebookLM notebook.
Uses notebooklm-py CLI for zero-manual-upload workflow.

Features:
- Auto-upload on generation complete
- Dedicated notebook: "OMNI_01 - Job Applications Archive"
- Organized by company/role
- Searchable via NotebookLM Q&A
- All processing local until upload (privacy maintained)
"""

import subprocess
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict


class NotebookLMIntegration:
    """
    Automatic NotebookLM integration for resume builder.
    Uploads all generated CVs and cover letters to dedicated notebook.
    """

    def __init__(
        self,
        storage_path: Optional[str] = None,
        notebook_title: str = "OMNI_01 - Job Applications Archive",
    ):
        """
        Initialize NotebookLM integration.

        Args:
            storage_path: Path to notebooklm storage file (default: ~/.notebooklm/storage_state.json)
            notebook_title: Title of dedicated notebook for applications
        """
        self.storage_path = storage_path or str(
            Path.home() / ".notebooklm" / "storage_state.json"
        )
        self.notebook_title = notebook_title
        self.notebook_id: Optional[str] = None

        # Check authentication
        self.authenticated = self._check_auth()

        if self.authenticated:
            # Get or create dedicated notebook
            self.notebook_id = self._get_or_create_notebook()

            print("✅ NotebookLM Integration initialized")
            print(f"   📓 Notebook: {notebook_title}")
            print(f"   🆔 ID: {self.notebook_id}")
            print(f"   💾 Storage: {self.storage_path}")
        else:
            print("⚠️  NotebookLM not authenticated")
            print(f"   Run: uv run notebooklm --storage {self.storage_path} login")

    def _run_notebooklm(
        self, args: list, capture: bool = True, timeout: int = 120
    ) -> subprocess.CompletedProcess:
        """Run notebooklm CLI command"""
        cmd = ["uv", "run", "notebooklm", "--storage", self.storage_path] + args
        try:
            result = subprocess.run(
                cmd, capture_output=capture, text=True, timeout=timeout
            )
            return result
        except subprocess.TimeoutExpired:
            return subprocess.CompletedProcess(cmd, -1, "", "Timeout")
        except FileNotFoundError:
            return subprocess.CompletedProcess(cmd, -1, "", "notebooklm not found")

    def _check_auth(self) -> bool:
        """Check if NotebookLM is authenticated"""
        result = self._run_notebooklm(["auth", "check"])
        return "Authentication is valid" in result.stdout

    def _get_notebook_id(self, title: str) -> Optional[str]:
        """Get notebook ID by title"""
        result = self._run_notebooklm(["list"])
        for line in result.stdout.split("\n"):
            if title.lower() in line.lower() and ":" in line:
                return line.split(":")[0].replace("•", "").strip()
        return None

    def _create_notebook(self, title: str, description: str = "") -> Optional[str]:
        """Create new notebook"""
        result = self._run_notebooklm(["create", title])
        for line in result.stdout.split("\n"):
            if "Created notebook:" in line and ":" in line:
                parts = line.split(":")
                if len(parts) >= 2:
                    nb_id = parts[1].strip().split(" - ")[0].strip()
                    print(f"   ✨ Created notebook: {nb_id}")
                    return nb_id
        return None

    def _get_or_create_notebook(self) -> Optional[str]:
        """Get existing notebook or create new one"""
        # Try to find existing
        nb_id = self._get_notebook_id(self.notebook_title)
        if nb_id:
            print(f"   📖 Found existing notebook: {nb_id}")
            return nb_id

        # Create new
        description = "Archive of all job applications, tailored resumes, and cover letters generated by Local Resume Builder"
        nb_id = self._create_notebook(self.notebook_title, description)

        if nb_id:
            # Upload initial description
            readme_content = f"""# {self.notebook_title}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Purpose:** Archive of all job applications, tailored resumes, and cover letters generated by Local Resume Builder.

**Features:**
- Automatic upload on generation
- Organized by company/role
- Searchable via NotebookLM Q&A
- All resumes and cover letters stored here

**Integration:** docs.bitandmortar.com (Local Resume Builder)
"""
            # Save and upload readme
            readme_path = Path("/tmp/notebooklm_readme.md")
            readme_path.write_text(readme_content)
            self.upload_source(readme_path, "README.md")

        return nb_id

    def upload_source(self, file_path: Path, custom_name: Optional[str] = None) -> bool:
        """
        Upload file to notebook.

        Args:
            file_path: Path to file to upload
            custom_name: Custom name for the source (optional)

        Returns:
            True if upload successful
        """
        if not self.notebook_id:
            print("❌ No notebook available")
            return False

        if not file_path.exists():
            print(f"❌ File not found: {file_path}")
            return False

        # Check file size (NotebookLM limit: 5MB)
        max_size = 5 * 1024 * 1024
        if file_path.stat().st_size > max_size:
            print(
                f"⚠️  File too large: {file_path.name} ({file_path.stat().st_size / 1024 / 1024:.1f}MB > 5MB)"
            )
            return False

        # Upload
        cmd_args = ["source", "add", "--notebook", self.notebook_id, str(file_path)]
        result = self._run_notebooklm(cmd_args, timeout=120)

        success = result.returncode == 0 or "Added source:" in result.stdout

        if success:
            source_name = custom_name or file_path.name
            print(f"   ✅ Uploaded: {source_name}")
        else:
            print(
                f"   ❌ Upload failed: {result.stderr[:200] if result.stderr else 'Unknown error'}"
            )

        return success

    def upload_application(
        self,
        company: str,
        role: str,
        resume_path: Path,
        cover_letter_path: Optional[Path] = None,
        job_description: Optional[str] = None,
    ) -> Dict:
        """
        Upload complete job application to NotebookLM.

        Args:
            company: Company name
            role: Job title/role
            resume_path: Path to tailored resume
            cover_letter_path: Path to cover letter (optional)
            job_description: Job description text (optional)

        Returns:
            Upload result dictionary
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        result = {
            "company": company,
            "role": role,
            "timestamp": timestamp,
            "resume_uploaded": False,
            "cover_letter_uploaded": False,
            "job_desc_uploaded": False,
            "errors": [],
        }

        # Upload resume
        if resume_path.exists():
            resume_name = f"{company}_{role}_Resume_{timestamp}.md"
            result["resume_uploaded"] = self.upload_source(resume_path, resume_name)
        else:
            result["errors"].append(f"Resume not found: {resume_path}")

        # Upload cover letter
        if cover_letter_path and cover_letter_path.exists():
            cl_name = f"{company}_{role}_CoverLetter_{timestamp}.md"
            result["cover_letter_uploaded"] = self.upload_source(
                cover_letter_path, cl_name
            )

        # Upload job description (if provided)
        if job_description:
            jd_path = Path(f"/tmp/{company}_{role}_JobDesc_{timestamp}.md")
            jd_content = f"""# Job Description: {role} @ {company}

**Generated:** {timestamp}

{job_description}
"""
            jd_path.write_text(jd_content)
            jd_name = f"{company}_{role}_JobDescription_{timestamp}.md"
            result["job_desc_uploaded"] = self.upload_source(jd_path, jd_name)
            jd_path.unlink()  # Clean up temp file

        # Upload summary metadata
        metadata_content = f"""# Application Summary

**Company:** {company}
**Role:** {role}
**Date:** {timestamp}

## Documents
- Resume: {resume_name if result['resume_uploaded'] else 'Not uploaded'}
- Cover Letter: {cl_name if result.get('cover_letter_uploaded') else 'Not uploaded'}
- Job Description: {jd_name if result.get('job_desc_uploaded') else 'Not uploaded'}

## Status
- Resume Uploaded: {'✅' if result['resume_uploaded'] else '❌'}
- Cover Letter Uploaded: {'✅' if result.get('cover_letter_uploaded') else '❌'}
- Job Description Uploaded: {'✅' if result.get('job_desc_uploaded') else '❌'}

---
*Generated by Local Resume Builder (docs.bitandmortar.com)*
"""
        metadata_path = Path(f"/tmp/{company}_{role}_Summary_{timestamp}.md")
        metadata_path.write_text(metadata_content)
        self.upload_source(metadata_path, f"{company}_{role}_Summary_{timestamp}.md")
        metadata_path.unlink()

        return result


# Global instance
_notebooklm: Optional[NotebookLMIntegration] = None


def get_notebooklm_integration() -> NotebookLMIntegration:
    """Get or create global NotebookLM integration instance"""
    global _notebooklm
    if _notebooklm is None:
        _notebooklm = NotebookLMIntegration()
    return _notebooklm


def upload_generated_application(
    company: str,
    role: str,
    resume_path: Path,
    cover_letter_path: Optional[Path] = None,
    job_description: Optional[str] = None,
) -> Dict:
    """
    Convenience function to upload generated application to NotebookLM.

    Args:
        company: Company name
        role: Job title
        resume_path: Path to resume
        cover_letter_path: Path to cover letter
        job_description: Job description text

    Returns:
        Upload result dictionary
    """
    integration = get_notebooklm_integration()
    return integration.upload_application(
        company, role, resume_path, cover_letter_path, job_description
    )


if __name__ == "__main__":
    # Test NotebookLM integration
    print("🚀 Testing NotebookLM Integration")
    print("=" * 60)

    # Initialize
    integration = NotebookLMIntegration()

    if not integration.authenticated:
        print("\n❌ NotebookLM not authenticated. Please run:")
        print("   uv run notebooklm --storage ~/.notebooklm/storage_state.json login")
    else:
        print("\n✅ Authenticated")
        print(f"📓 Notebook ID: {integration.notebook_id}")

        # Test upload (if test files exist)
        test_resume = Path(
            "/Volumes/OMNI_01/10_SOURCE/10_Front_Gate/public/apps/local-resume-builder/my_documents/cv_applications/satsyil_corp_databricks_architect_cv.md"
        )
        test_cl = Path(
            "/Volumes/OMNI_01/10_SOURCE/10_Front_Gate/public/apps/local-resume-builder/my_documents/cv_applications/satsyil_corp_databricks_architect_cover_letter.md"
        )

        if test_resume.exists():
            print(f"\n📄 Testing upload with: {test_resume.name}")
            result = integration.upload_application(
                company="Satsyil Corp",
                role="Senior Databricks Architect",
                resume_path=test_resume,
                cover_letter_path=test_cl,
                job_description="Senior Databricks Architect position requiring Spark, Python, and ETL expertise",
            )

            print("\n✅ Upload Result:")
            print(f"   Resume: {'✅' if result['resume_uploaded'] else '❌'}")
            print(
                f"   Cover Letter: {'✅' if result.get('cover_letter_uploaded') else '❌'}"
            )
            print(
                f"   Job Description: {'✅' if result.get('job_desc_uploaded') else '❌'}"
            )
